name: Déploiement du site statique

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Vérification du dépôt
      uses: actions/checkout@v2

    - name: Déploiement via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: ./
        server-dir: /public_html/
        args: --delete
